import requests
import argparse
import sys
import time
import wave
import struct
import os

def create_dummy_wav(filename="test_audio.wav", duration=1.0):
    """Creates a 1-second silent WAV file for testing."""
    sample_rate = 24000
    num_samples = int(duration * sample_rate)
    with wave.open(filename, 'w') as wav_file:
        wav_file.setnchannels(1)
        wav_file.setsampwidth(2)
        wav_file.setframerate(sample_rate)
        # Write silence
        data = struct.pack('<' + ('h' * num_samples), *[0] * num_samples)
        wav_file.writeframes(data)
    return filename

def test_gateway(admin_secret, base_url):
    print(f"🔍 Testing Gateway at {base_url}...")
    
    # 1. Health Check
    print("\n1️⃣  Checking Health...")
    try:
        resp = requests.get(f"{base_url}/health")
        if resp.status_code == 200:
            print("   ✅ Service is UP")
            print(f"   ℹ️  Details: {resp.json()}")
        else:
            print(f"   ❌ Health check failed: {resp.status_code} - {resp.text}")
            return
    except requests.exceptions.ConnectionError:
        print(f"   ❌ Could not connect to {base_url}. Is the server running?")
        return

    # 2. Admin: List Keys
    print("\n2️⃣  Testing Admin Auth (List Keys)...")
    headers = {"X-Admin-Secret": admin_secret}
    resp = requests.get(f"{base_url}/admin/keys", headers=headers)
    
    if resp.status_code == 403:
        print("   ❌ Access Denied: Incorrect Admin Secret.")
        return
    elif resp.status_code == 200:
        keys = resp.json().get("keys", [])
        print(f"   ✅ Auth Success. Found {len(keys)} existing keys.")
    else:
        print(f"   ❌ Unexpected Error: {resp.status_code} - {resp.text}")
        return

    # 3. Admin: Generate New Test Key
    print("\n3️⃣  Generating Temporary Test Key...")
    test_key_name = f"test-script-{int(time.time())}"
    resp = requests.post(
        f"{base_url}/admin/keys/generate", 
        headers=headers,
        data={"name": test_key_name, "description": "Generated by test_gateway.py"}
    )
    
    if resp.status_code == 200:
        data = resp.json()
        api_key = data["api_key"]
        print(f"   ✅ Key Generated: {api_key}")
    else:
        print(f"   ❌ Failed to generate key: {resp.text}")
        return

    # 4. Inference Test (Offline)
    print("\n4️⃣  Testing Offline Inference...")
    wav_file = create_dummy_wav()
    print(f"   ℹ️  Created dummy audio file: {wav_file}")
    
    try:
        with open(wav_file, 'rb') as f:
            resp = requests.post(
                f"{base_url}/v1/inference",
                headers={"X-API-Key": api_key},
                files={"audio": f},
                data={"persona": "Testing", "voice": "NATF2"}
            )
        
        if resp.status_code == 200:
            output_file = "test_response.wav"
            with open(output_file, 'wb') as f:
                f.write(resp.content)
            print(f"   ✅ Inference Success!")
            print(f"   💾 Saved response to: {output_file}")
            print(f"   📝 Transcript header: {resp.headers.get('X-Transcript', 'N/A')}")
        elif resp.status_code == 500:
             print(f"   ⚠️  Request reached server but inference failed (expected if Moshi not running locally).")
             print(f"   ℹ️  Server Error: {resp.json().get('detail')}")
        else:
            print(f"   ❌ Inference Request Failed: {resp.status_code} - {resp.text}")

    finally:
        # Cleanup
        if os.path.exists(wav_file):
            os.remove(wav_file)
            print(f"   🧹 Cleaned up {wav_file}")

    # 5. Cleanup Key
    print("\n5️⃣  Revoking Test Key...")
    resp = requests.post(
        f"{base_url}/admin/keys/revoke",
        headers=headers,
        data={"api_key": api_key}
    )
    if resp.status_code == 200:
        print("   ✅ Test Key Revoked.")
    else:
        print(f"   ⚠️  Failed to revoke key: {resp.text}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Test PersonalPlex Gateway")
    parser.add_argument("--secret", help="Admin Secret", required=True)
    parser.add_argument("--url", help="Gateway URL", default="http://localhost:8000")
    
    args = parser.parse_args()
    
    test_gateway(args.secret, args.url)
